### ISSUE TITLE
Trackpad Dragging Stops Working

### ISSUE THREAD

**Issue by keysun11952** [jardenliu/XPS15-9560-Catalina#124]
This was not an issue in version 4614655411a1b3a3b32c14e5d8e1e8851d91c07b
It comes with 174d8a1647939e5570a2e0e576872f41e364b6fb in which Voodoo Kext was updated
Trackpad dragging no longer works in "double tap and drag" mode
Three finger dragging still works and same with all other gestures

**Comment by jardenliu** [comment]
In my laptop , `double-tap-to-drag` is work fine.

Have you ever enabled this option？

steps as follow:

`System Preferences → Accessibility → Pointer Control → Mouse & Trackpad → Trackpad Options…
Enable dragging → With Drag Lock per your preference`

**Comment by keysun11952** [comment]
Yep I have. And it worked in the previous version 4614655411a1b3a3b32c14e5d8e1e8851d91c07b

**Comment by jardenliu** [comment]
It work fine in my laptop. What's the verison of VoodooI2C which you used?

**Comment by nlimbo** [comment]
If you have enabled tap to click in trackpad option, re-enable it after disabling it. That fixed the problem. My problem was that the click(not tap) was working as three-finger tap so that I couldn't drag stuff while clicking. After rechecking the tap to click, it works fine now.

<img width="671" alt="스크린샷 2020-05-02 오후 2 08 23" src="https://user-images.githubusercontent.com/38833250/80855707-64046900-8c7e-11ea-8387-94a478c21ab2.png">
(third checkbox in the picture)

**Comment by keysun11952** [comment]
Updating Voodoo kext fixed this issue. Thanks everyone!
